global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'tf-serving'
    metrics_path: /monitoring/prometheus/metrics
    static_configs:
      - targets: ['tf-serving:8501']
