apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-serving
  template:
    metadata:
      labels:
        app: tf-serving
    spec:
      containers:
        - name: tf-serving
          image: tensorflow/serving
          env:
            - name: MODEL_BASE_PATH
              value: /models
            - name: MODEL_NAME
              value: fosm
          volumeMounts:
            - name: model-volume
              mountPath: /models/fosm
          ports:
            - containerPort: 8501
              name: http
            - containerPort: 8500
              name: grpc
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: fosm-models
---
apiVersion: v1
kind: Service
metadata:
  name: tf-serving
spec:
  selector:
    app: tf-serving
  ports:
    - port: 8501
      targetPort: http
      name: http
    - port: 8500
      targetPort: grpc
      name: grpc
