# Default training configuration

defaults:
  - data: default
  - model: classical/random_forest
  - features: default
  - _self_

mlflow:
  tracking_uri: "file:mlruns"
  experiment_name: fosm-training

train:
  test_size: 0.2
  threshold_metric: f1
  run_name: training-run

artifacts_dir: models/latest

expectations:
  expectations:
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        column: "value"
    - type: "expect_column_values_to_be_between"
      kwargs:
        column: "value"
        min_value: -10
        max_value: 10

hydra:
  run:
    dir: .
  output_subdir: null
